language: objective-c
osx_image: xcode7.3
before_install: rvm use $RVM_RUBY_VERSION
install: gem install slather
script: xcodebuild -project Logopeda.xcodeproj -scheme Logopeda -sdk iphonesimulator9.3 test 
after_success: slather
notifications:
  slack:
    secure: qXfW1tlFjgv54eR//eN2r0LrtUONn94PhhcO5U/azIk/xrZ36NNyPTOfpLkxmk5Q6FU5x3Bxjw6asifkTy7K1kMX6NAylStTSBYo3jUBDo+l6kzvILuHXYZZVmwDkc59e9koXSbUFTqZHqa9lPghrqgCJCA3hTm/6AwEZbBsIPuB8yhBkj+DmvPgt1zVKcDHYXwJ3UnQkyV5UtWHaaX8MwkNtToiaNyphxeKNrcPN0huT1BSgdb7cZo8J3hNPTl8kgAx5DI/CHvze/8gTMtXw+Gw95mfVmjjbxDpAXA35t9iRFhVUsp2Cafwr5up7gqAylZ8flqJKXejNqbf26m8VRR3oYxEHnxz3MBNBb4GccKalEA0IdUdLNJuZsENfsdM7Z52URB3tWZvwtqQ9AiSB+/coy/amtID7PXTc8rPiww8Y3ax2VEYGy4ty2Y+5M8w6aSEYeTSxS8xGathbcEz6Mg/wW90N4emSmXBkVYWkbkjjUejUhkIAmqBX6a3wKs8jz8S8Oby2AW1MbNKeHyLDSJ1y9UwO11t2nyAiEyMTXboHDcw3LjGQeh9imze2iTirGUp68QHd2fzGlKvsWHrhKuau1lPdNmcj+WEU38LRRLD1K/25k73LK0AUVcEWVT2zrW3k9z61oGvmicji3tHkAguF75m5yBR0eLPko9wUR0=
